### ISSUE TITLE
Suggestion - Blockhit

### ISSUE THREAD

**Issue by paipaint** [b1scoito/clicker#19]
Was either thinking if you could make it so it detects when the autoclicker should blockhit for the perfect blockhit. (Basically smart blockhit that drip lite has) or that you could make a autoblock which you could set a second timer on so every for example 2 seconds it presses right click.

**Comment by mattys0229** [comment]
after sendinput lbutton write sendinput rbutton

**Comment by b1scoito** [comment]
Added.
