### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by owoian** [b1scoito/clicker#20]
![image](https://user-images.githubusercontent.com/74127519/98457928-d2e2f180-21ce-11eb-911c-189febcfbced.png)
This is my setting. After I press G, I pressed my mouse but it didn't do anything. Did I make mistake?

**Comment by sponje** [comment]
Enable it

**Comment by 800f** [comment]
Doesn't work

**Comment by b1scoito** [comment]
It's disabled.
