### ISSUE TITLE
Not Working Windows 10 

### ISSUE THREAD

**Issue by bootysquirt711** [b1scoito/clicker#21]
Set keybind, set to Minecraft and change the sliders but it is not working

**Comment by b1scoito** [comment]
Can you please be more specific?

**Comment by bootysquirt711** [comment]
The autoclicker wont work. I have set everything and tried it in minecraft. held down the left click and not work. CPS counter also does not change and sword not swing

**Comment by b1scoito** [comment]
Please download the new version and try enabling it first. Check if your window is set correctly.
