### ISSUE TITLE
Second Monitor bug

### ISSUE THREAD

**Issue by evapey** [b1scoito/clicker#22]
if i put the clicker on my second monitor it locks my main monitor's refresh rate to that monitor's refresh rate (60hz)

**Comment by b1scoito** [comment]
Can you please run the debug build and show me the framerate on both monitors?

**Comment by evapey** [comment]
![image](https://user-images.githubusercontent.com/34406978/108048924-89ad0400-703f-11eb-99db-7cfbc1c49a52.png)
main monitor
![image](https://user-images.githubusercontent.com/34406978/108048965-97fb2000-703f-11eb-9df3-f3e16d272fc3.png)
second monitor

**Comment by b1scoito** [comment]
This is rather interesting. I don't really know what might be causing it. It's not really my issue, probably is something about creating the DX9 renderer, I don't have high refresh rate monitors so I can't really test it, But I'll try to look into it somehow. Until then just use it on your main monitor.

**Comment by b1scoito** [comment]
Take a look at this: https://github.com/ocornut/imgui/issues/2970#issuecomment-596778325

**Comment by b1scoito** [comment]
Should be fixed on this new release.
