### ISSUE TITLE
May I know how to compile this on Ubuntu 20.04

### ISSUE THREAD

**Issue by freeze-dolphin** [b1scoito/clicker#23]
I know nothing about C++ so that I an wondering how to compile it to make it run on my Ubuntu. 

I've tried cmake and make but it didn't work.

**Comment by ponei** [comment]
pretty sure compiling wouldn't work either way. this project uses windows specific functions (https://github.com/b1scoito/clicker/blob/master/def/includes.hpp, windows header) for sending input and messing with memory. changes could be made to support linux, but I'm not sure if this feature is on a todo list.

**Comment by b1scoito** [comment]
Linux support is not close by any means.
