### ISSUE TITLE
Bedrock edition support

### ISSUE THREAD

**Issue by SomeRandomGithub-User** [b1scoito/clicker#26]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
can you add bedrock edition support

**Additional context**

**Comment by b1scoito** [comment]
What doesn't work there?

**Comment by SomeRandomGithub-User** [comment]
oh ill test it

**Comment by SomeRandomGithub-User** [comment]
Yeah doesnt work on bedrock edition posting video rn

**Comment by b1scoito** [comment]
Can you send a video demonstrating your issue and showing your config please?

**Comment by SomeRandomGithub-User** [comment]
https://streamable.com/w35m9i
If you look at the clicks it's going up rapidly but in-game the clicks dont work

**Comment by b1scoito** [comment]
I might be wrong but, as Minecraft Bedrock edition is a game in the Windows store, it most likely uses UWP (Universal Windows Platform) and UWP runs inside a "sandbox", therefore, the clicks might not being registered.

This cannot be fixed unless I send and receive mouse and keyboard calls from kernel, which is not really practical.

**Comment by SomeRandomGithub-User** [comment]
do i close this
