### ISSUE TITLE
Virus Flag on Windows 10

### ISSUE THREAD

**Issue by VeniVidiViciVersace** [b1scoito/clicker#27]
**Describe the bug**
The program flags malware detection on Windows 10 (auto-removes from computer), and flags many other security programs on VirusTotal. This is specific to the latest release - problem didn't exist in previous releases.

Screenshot:
https://i.imgur.com/d1F2Qjz.png

**Desktop (please complete the following information):**
 - Windows 10

**Comment by b1scoito** [comment]
It's open-source. If you compare all symbols on the compiled release and a self-compiled they will match.

Anti-virus engines _will_ false-flag because of the low-level keyboard hooking and mouse. This is not an issue nor can it be fixed.
