### ISSUE TITLE
Suggestion - Inventory

### ISSUE THREAD

**Issue by MiroLpb** [b1scoito/clicker#29]
Is it possible to add an option where we can choose in which slots of the inventory the autoclick works

**Comment by MiroLpb** [comment]
please

**Comment by b1scoito** [comment]
Bit annoying to implement externally, I'm probably not going to do it

**Comment by EtienneRld** [comment]
Hello ! I have did it myself and it work perfectly.

There are just 2 small problems:
- If I change world, the application will not follow the new slot directly, the user will have to press a hotbar slot key to synchronize the application again with the current slot.

- If I scroll my mouse wheel too fast, the application will not give the correct slot. (But you have to be really fast to do it)

So to achieve this I did:
- A WH_MOUSE_LL callback to intercept mouse wheel change.
- I added the 9 vkCode for the hotbar slot keys in the keyboard callback.
- I added a section in the gui with checkboxes for slots, right click and left click.
- I added some conditions to click related to the slot.
- I added also a Text to show the actual slot in game.
- And somes variables.

Can I deposit my changes / the entire edited projet here ?
Also you can add me on Discord: Etienne#0003 (My hashtag will change in a few days).

**Comment by b1scoito** [comment]
Hello — Thanks for the help, but

Having a mouse hook will start the mouse flickering issue again. Basically what happens is, the thread gets suspended for the processor to process other threads, as everything mouse-related passes through the mouse hook function, Minecraft will not register the mouse movement correctly and will flick the mouse.

With lower-end PCs that will be a big issue.

Making an external slot detector is just too annoying to implement, I would love to see your Contribution in the project, but given the current circumstances, I cannot accept it. You can, however, make a fork with that function implemented, so other users can use that functionality.

**Comment by EtienneRld** [comment]
Thank you for having answered me quickly, I had not taken into consideration this problem.

When I have time, I will create a fork.
