### ISSUE TITLE
2 issues.

### ISSUE THREAD

**Issue by voltymtt** [b1scoito/clicker#3]
First, when I drag the max cps slider it also drags min cps slider then I cant change it back.

Second, I cant get the auto clicker working on Lunar (IDK if supported).

PCE,
VoltY

**Comment by Maavari** [comment]
min and max sliders are labeled wrong, top is max and bottom is min

**Comment by b1scoito** [comment]
i'll fix the order of the sliders and how they work, about lunar it should work, make sure you're opening it as admin, i'll test it.

**Comment by b1scoito** [comment]
Lunar seems to be working fine i don't know why it isn't working with you https://streamable.com/us4x06
