### ISSUE TITLE
Porlbemas com o software (probmeas serios) eu preciso q fixe 

### ISSUE THREAD

**Issue by cincovp** [b1scoito/clicker#31]
Entao Venho aqui relatar alguns bug q encotrei ao testar esse softwrae .

Eu copile ida source e noitei uns porlbemas serios q podem atrapalar o uso dos usuarios e tal

Um dos maores porlbemas eh q essa poha nao abre. fica crashasndo essa merda n abre nunca esa porra . fica dando nao repsondendo toda hora q eu abro e nao da pra usar e uma vez deu tela azul no meu pc...

Segundo, eu nao consiga compilar essa merda. nao compila fica dnado erra e nao da pra compilar nunca e fica travando o Cmake e nao compila e crasha qnd compila

Terceira. Ao abrir buga tudo e fica tudo bugado meu mouse fica mexendo sozinho n consigo mexer na merda do PC mais

Quarta. Meu discord fica madando msg pra todo mundo falando q eh viado dps q eu abri essa merda ta bughado essa porra

Vlw. Consertar o bugs

estarei postado uma foto do meu pc para ajudar na pesquisa e conserto de bugs. vai q ajuda. as specs estao na foto.
![meuPC](https://user-images.githubusercontent.com/53921095/126947168-88a4dabb-8a45-4199-935a-1fa2dc3a957b.png)

**Comment by happylukah** [comment]
acho que e a windoas. so atualiza para windaws7

**Comment by b1scoito** [comment]
Estarei fixando esssa pohha desse bug ai mais tarde pq agr eu to com preguica pra krl

Etava esperando pelo report tao bom com,o esse omuito ibrigado

**Comment by cincovp** [comment]
criol umas pastas no meu desktop tambem com o nome Nova pasta e esta enchendo meu dsico rrigido de CP. nao consigo parar precisa da ajuda dos devs.

**Comment by b1scoito** [comment]
Vlw man

**Comment by b1scoito** [comment]
Epera 1 poko q estarei fixando essa pohha ghr msm

**Comment by happylukah** [comment]
kkk

**Comment by cincovp** [comment]
outro problema eh q Trava a poha do meu pc todo e nao da pra usar alem de nao abrir minh CPU fica 100 o tempo todo e nao da pra abrir o Face, Orkut etc fica travando e c rahsando essa merda eu preciso mexer nos arquivos do trampo e Nao consigo mexer no meu micro. Eh necessario q rseolva rapido pois a padaria aqui esta com a poha de uma fila jigante e a merda Do pc aki todo travado nao consigo passar As bisnagas e nem Gerar recibos.

**Comment by b1scoito** [comment]
To ligando

**Comment by b1scoito** [comment]
![spycrab](https://user-images.githubusercontent.com/17802984/126947825-1c4e17fa-358f-466f-9e6e-4166646ec9bc.png)

**Comment by happylukah** [comment]
![download](https://user-images.githubusercontent.com/52342023/126947852-a04550a4-1437-4dab-9a1f-1bdb4746ef6e.jpg)

**Comment by cincovp** [comment]
alias eu Quero saber quando receberei Meu iPone . qnd abri o pograma pela primeira vez foi prometido um iPone 4 ao clicar no Link. ao Clicar no link foi descontado do meu Cheque Especial 20 Mil reais e ainda esotu esperando meu iPone 4.

**Comment by cincovp** [comment]
alias outro problema Onde bota o arquivo .Sln . qnd eu tento abrir ele Abre um visuel studio nao sei usa esa merda . Eh pra abrir como Admin? onde eh pra bota os arguivos

**Comment by b1scoito** [comment]
Teta como abrir como UAC

**Comment by b1scoito** [comment]
(User Account Manager)

**Comment by b1scoito** [comment]
Bon, eu imagini que tenha fixado este bug, poren estou ainda supreso pelos bugs do iPone, poren irei tetar adicioanr este bug de volta pois ele muto bom ok porlbema fixado ok
