### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by paipaint** [b1scoito/clicker#34]
possibly add a "best time blockhit" feature where the clicker automatically blockhits at the perfect time to get a combo going

**Comment by b1scoito** [comment]
What is "Perfect time"?

**Comment by paipaint** [comment]
Sorry that it took a while for me to respond, if you go to this video (I couldn't find any other examples) https://www.youtube.com/watch?v=7HVVQ6o7GRs&t=281s&ab_channel=PuffedUp and go to 2:57, then continue watching until he starts fighting an opponent the program automatically blockhits for him at the perfect time to get a combo.

**Comment by b1scoito** [comment]
I've got no time at the moment, even though, I still think it's not possible to do it.
