### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SynnKFPS** [b1scoito/clicker#37]
- Add 'Break Blocks' option, which will check if you're aiming to a block, if so, you can break the block (instead disable for it) (ik that hotkey is better but UH);
- Add 'Consume' option, which will allow you to consume soup, potions, gapples, etc;
- Add 'Sound Indicator' (maybe in misc options), which will play a sound every time you enable/disable the clicker;
- Add 'Screen Indicator' which will render a text on your screen to indicate if the clicker is on or off;

I guess that 'break blocks' and 'consume' option is a little impossible to implement because it will need to get what you're holding to check or if you are aiming to a block, but those will be a good setting if possible to add

**_sorry for my english, i'm not good at it_**

**Comment by b1scoito** [comment]
You're right, but I still have no idea on how I would detect consumable items externally.
