### ISSUE TITLE
cps error

### ISSUE THREAD

**Issue by Technosteve942** [b1scoito/clicker#40]
does not go above 10 cps in 1.11
i have set is to 20 with spike 100% 5cps

**Comment by b1scoito** [comment]
Please show me your settings with a screenshot and if possible send me a video that I can see your issue.

**Comment by Technosteve942** [comment]
https://user-images.githubusercontent.com/69840732/144546368-cb46430a-8750-47fe-8ff1-d60bd47f5cf7.mp4

see 
i used th 1.9 it gave me 25 cps
but this gave me 15 cps

**Comment by b1scoito** [comment]
Seems about right to me, some of that imperfection is due to the CPS Mod or even your windows scheduling, try Ctrl + Clicking the slider for custom values if you want a higher CPS.

**Comment by Technosteve942** [comment]
again getting 10 cps after few min

**Comment by b1scoito** [comment]
When you say you're getting lower CPS on specific times, seems to me that your processor is hanging the clicker thread for processing other heavy thread such as Minecraft.

**Comment by Technosteve942** [comment]
> 

thanks i did not knew we can put custom value

**Comment by b1scoito** [comment]
Yes you can, if you hover on `Clicker configuration` you can see that.

**Comment by Technosteve942** [comment]
its virus free now 
actually what happened is that the clicker tried to mess with mouse config and my anti virus doesnt like it so

**Comment by spencer1911** [comment]
please learn spike function.
