### ISSUE TITLE
just dont work on other apps which it's not minecraft

### ISSUE THREAD

**Issue by skhrlx** [b1scoito/clicker#41]
![image](https://user-images.githubusercontent.com/85849948/147497671-bdfd6532-5491-44df-a8a6-d219e42afeb7.png)

Just don't work on other apps which it's not minecraft

**Comment by b1scoito** [comment]
This happens mainly because the WINAPI function `SendMessageA` doesn't like to work on normal windows, a switch for SendInput will be added on the next update.

Something advanced for sending inputs can be thought out too.

**Comment by skhrlx** [comment]
Thanks for the support, you are the best.
