### ISSUE TITLE
Hello sar you have virus

### ISSUE THREAD

**Issue by 151kmh** [b1scoito/clicker#46]
This program has virus. Look is proof
![image](https://user-images.githubusercontent.com/102869428/198850060-8fcf1a89-ae39-40c0-af13-bd8bbbcf2242.png)
Is vrius total. Malware trojan want to break cumputer.

**Comment by b1scoito** [comment]
Please refer to these previously made issues: #28 #27 #33 #39 #42

Those are false flags, this project is fully open-source, you can compile it yourself and use it.
