### ISSUE TITLE
Is it possible to use this on a mac?

### ISSUE THREAD

**Issue by ttuleyb** [b1scoito/clicker#50]
As title suggests, I'm trying to use this on a mac. I think the only changes that have to be done are to the mouse API (which is probably most of the program), I'm going to look into it, appreciate if anyone else has info on this.

**Comment by ttuleyb** [comment]
Upon further consideration, also need to change keyboard APIs and find a way to grab keyboard input while the window isn't focused, which is possible because programs like https://www.murgaa.com/auto-clicker-mac/ exist and works on my mac.

**Comment by b1scoito** [comment]
First, we would need to port the project to either CMake or Meson, for it to be more flexible on the cross-compilation, alongside with that, use Clang with LLVM, then we would need to change all the functions that use WinAPI functions to a custom macro? that gives the correct function depending on the operating system. This includes [`to_unicode`](https://github.com/b1scoito/clicker/blob/master/clicker/utils.cpp#L6), [`send_input`](https://github.com/b1scoito/clicker/blob/master/clicker/utils.cpp#L42), [`convert_wm_to_mouseeventf`](https://github.com/b1scoito/clicker/blob/master/clicker/utils.cpp#L65), [`active_window_title`](https://github.com/b1scoito/clicker/blob/master/clicker/utils.cpp#L82), [`is_self_focused`](https://github.com/b1scoito/clicker/blob/master/clicker/utils.cpp#L94), [`is_cursor_visible`](https://github.com/b1scoito/clicker/blob/master/clicker/utils.cpp#L106), [`window_think`](https://github.com/b1scoito/clicker/blob/master/clicker/utils.cpp#L119), https://github.com/b1scoito/clicker/blob/master/clicker/main.cpp#L16, we'd also need to change how ImGui gets initialized, for macOS, for example, we would use Metal ideally or OpenGL for cross-compatibility between *nix and Windows. https://github.com/b1scoito/clicker/blob/master/clicker/menu.cpp#L592, the logger needs to be changed to support that too. Third-party libraries can be used. https://github.com/b1scoito/clicker/blob/master/clicker/console.hpp#L55, The config system still uses an Windows API call: https://github.com/b1scoito/clicker/blob/master/clicker/config.cpp#L6, and the clicker function uses [GetAsyncKeyState](https://github.com/b1scoito/clicker/blob/master/clicker/clicker.cpp#L121).

In the end, we just need to wrap all functions around an universal function that executes a certain syscall for each operating system, and change ImGui to support OpenGL in a cross-platform way.

I have thought about making it cross-platform, but I think it would be way easier by rewriting it in Rust.
