### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by mK33y** [b1scoito/clicker#51]
This released files contains a trojan.

Trojan:Win32/Mamson.A!ac 
Trojan:Win32/Mamson.A!ac is a detection that corresponds to AgentTesla remote-access trojan (RAT). This malware is often used as a stage 1 malware in ransomware attacks, which preceeds the final payload. Using AgentTesla, hackers can prepair the system to accept further infections.

**Comment by b1scoito** [comment]
Please refer to these previously made issues: #28 #27 #33 #39 #42 #46

Those are false flags, this project is fully open-source, you can compile it yourself and use it.
