### ISSUE TITLE
hmhm

### ISSUE THREAD

**Issue by LexySC** [b1scoito/clicker#54]
If you look VirusTotal it says 43/71 detection.
But if you look AV Name's they are noname xd.

If you look ESET and Other AV's you can see, they say : GameTool/Riskware.
And if you look, you cant see that any antivirus definitely says virus. Most of them say "Behaves Like a Trojan" or smth like that.

And if you look Good AV's Like Kaspersky,BitDefender,Avira,ESET didnt detected it. 
![image](https://github.com/b1scoito/clicker/assets/112518723/eb601bd7-4db6-48f1-879f-93bff8651900)
Its first scan in VT 2022 to 2023.
So if you are talking about a virus these 4 high-quality antivirus company should not have done any tests on a file that has actually been used for 1 year.

And if you look Behaviour section you can see dropped files and if you look that all of these are temp files, you will see that he did not download the exe file.

**If you are very bipolar about viruses, compile the source code. And look the code.**

If you say the BitDefender,Kaspersky,Avira and ESET not good actually you can look tests xd. They are most popular AV products.
https://www.av-comparatives.org/tests/advanced-threat-protection-test-2022-consumer/
https://www.av-comparatives.org/tests/real-world-protection-test-july-october-2022/
https://www.av-comparatives.org/tests/malware-protection-test-march-2023/
https://www.av-comparatives.org/tests/false-alarm-test-march-2023/
https://www.av-test.org/en/news/fending-off-ransomware-even-against-state-of-the-art-attack-techniques/
https://www.av-test.org/en/news/security-from-data-stealers-so-sensitive-data-wont-end-up-on-the-darknet/

But to be sure of everything i finally did a Hybrid-Analysis test.
Windows 10 64 Bit and the settings: 
![image](https://github.com/b1scoito/clicker/assets/112518723/7f6c2f75-f051-4e0c-972d-245df642a12d)
the result
![image](https://github.com/b1scoito/clicker/assets/112518723/e58afc33-e566-491a-93b9-a35d0a28ad70)
![image](https://github.com/b1scoito/clicker/assets/112518723/eb840997-992c-4d41-9a9f-13b7e795f83b)
![image](https://github.com/b1scoito/clicker/assets/112518723/423b1fd8-4020-413e-a8ea-4753c69df2c6)
![image](https://github.com/b1scoito/clicker/assets/112518723/acdc00ad-9c8f-4a6e-91cf-645f9029aaf1)

and there is link: https://www.hybrid-analysis.com/sample/41f113612474cebdbccbe13e7543743a46806a5808b53390379f52ff176268e7/63c614e0815b07055a391c38
But idk why, i can see "some" really suspicious process.

If i give incorrect information, instead of swearing, please tell me where i did/thought wrong

**And sorry i say Clipboard to suspicious its because config system (or maybe im wrong)**

**Comment by b1scoito** [comment]
Please refer to these previously made issues: https://github.com/b1scoito/clicker/issues/28 https://github.com/b1scoito/clicker/issues/27 https://github.com/b1scoito/clicker/issues/33 https://github.com/b1scoito/clicker/issues/39 https://github.com/b1scoito/clicker/issues/42 https://github.com/b1scoito/clicker/issues/46

**Comment by zuyukii** [comment]
so is safe?

**Comment by b1scoito** [comment]
Yes.
