### ISSUE TITLE
Cant break blocks

### ISSUE THREAD

**Issue by zManix** [b1scoito/clicker#56]
Is it possible to add a feature that lets you mine blocks since the autoclicker doesent let you mine anything and is kinda impossible to play bedwars in this case

**Comment by zManix** [comment]
cant consume anything either, idk maybe theres a way to make it detect consumables and block breaking

**Comment by zManix** [comment]
maybe also only specific blocks as it might interfere with fighting otherwise

**Comment by b1scoito** [comment]
Break blocks feature can't be done in a reliable way since we're sending clicks externally, what you can do if you're not using the right auto-clicker is pressing the right mouse button while pressing the left the left-clicker will disable.

**Comment by zManix** [comment]
Yup been doing that instead, but it doesent work the other way around

**Comment by b1scoito** [comment]
> Yup been doing that instead, but it doesent work the other way around

In this case you can bind the right-mouse auto-clicker so you can disable whenever you need to use it.

**Comment by zManix** [comment]
not sure how to specifically bind trhe right mouse, do i have to have 2 instances open for that?

**Comment by b1scoito** [comment]
Oh. This project is so old I didn't remember I didn't have the feature to bind each one independently. I plan on making a rewrite of this project in the future, but nothing is guaranteed. The project is open-source anyways so if you want to learn something new, implement it and contribute to the project! :D.
