### ISSUE TITLE
Compatibiliy issue

### ISSUE THREAD

**Issue by asteroid14** [b1scoito/clicker#57]
I have tried using your name the tab method in the settings, but can't get the autoclicker to click on the game I'm trying to use it for. The game is bedrock edition of Minecraft. I know it's not exactly intended to work on that verison of Minecraft, but if you could fix it for that version it would be much appreciated.

**Comment by b1scoito** [comment]
https://github.com/b1scoito/clicker/issues/26#issuecomment-820871956
