### ISSUE TITLE
Windows 7 Compatibility (XINPUT1_4)

### ISSUE THREAD

**Issue by iDeagan** [b1scoito/clicker#6]
Hello, I am on windows 7 and windows 7 does not support XINPUT1_4. 

I attempted to find a work around, and i did. (i think)

in the imgui_impl_win32.cpp file, i commented out #pragma comment(lib, "xinput") (windows 8+), and uncommented #pragma comment(lib, "Xinput9_1_0") (Windows 7). after i did this i attempted to run  it and i got this error:

Exception thrown at 0x00D263BA in clicker.exe: 0xC0000005: Access violation reading location 0x0000003C.
Also got a warning in console:

Warning	C6011	Dereferencing NULL pointer 'Buf.Data'. 	clicker	C:\USERS\DEAGAN\DESKTOP\CLICKER-RELEASE\SOURCE\imgui.h	1714

Is there a workaround? am i missing something?

Regards,
Deagan.

**Comment by b1scoito** [comment]
The workaround is to downgrade the XINPUT version for that matter, i'll be pushing an update soon that will have some changes and fixes to the overall functionality of the clicker.

**Comment by b1scoito** [comment]
Also sorry for not seeing issues that frequently, i kinda left this project to the side

**Comment by TheMadHau5** [comment]
AFAIK, Windows 7 is now EOL and it shouldn't be used. Please upgrade to 10.

**Comment by b1scoito** [comment]
Coming back to this, I checked `imgui_impl_win32.cpp` and they theoretically load XINPUT dynamically depending on the system that it's running it, it should run just fine, but I'll test it later. 
```cpp
	// Dynamically load XInput library
#ifndef IMGUI_IMPL_WIN32_DISABLE_GAMEPAD
	const char *xinput_dll_names[] =
	{
		"xinput1_4.dll",   // Windows 8+
		"xinput1_3.dll",   // DirectX SDK
		"xinput9_1_0.dll", // Windows Vista, Windows 7
		"xinput1_2.dll",   // DirectX SDK
		"xinput1_1.dll"    // DirectX SDK
	};
	for ( int n = 0; n < IM_ARRAYSIZE( xinput_dll_names ); n++ )
		if ( HMODULE dll = ::LoadLibraryA( xinput_dll_names[ n ] ) )
		{
			g_XInputDLL = dll;
			g_XInputGetCapabilities = ( PFN_XInputGetCapabilities )::GetProcAddress( dll, "XInputGetCapabilities" );
			g_XInputGetState = ( PFN_XInputGetState )::GetProcAddress( dll, "XInputGetState" );
			break;
		}
#endif // IMGUI_IMPL_WIN32_DISABLE_GAMEPAD
```
